name: Test

on:
  pull_request:
  push:

jobs:
  unit_test:

    strategy:
      fail-fast: false
      matrix:
        node_version: [16, 18, 20]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm ci

      - run: npm t

  type_check:

    strategy:
      fail-fast: false
      matrix:
        node_version: [16, 18, 20]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm ci
      
      - run: npm run type-check
